name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes
        run: npm test

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Construir imagem Docker
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: lacrei-devsecops:latest

      - name: Executar aplicação
        run: |
          docker run -d --name lacrei-app -p 3000:3000 lacrei-devsecops:latest
          sleep 10
          docker ps -a
          echo "===== LOGS DA APLICAÇÃO ====="
          docker logs lacrei-app
          echo "===== TESTE HTTP ====="
          curl --fail http://localhost:3000/status

      - name: Executar OWASP ZAP
        run: |
          mkdir -p zap-report
          chmod 777 zap-report

          docker run --network host \
            -u zap \
            -v "${{ github.workspace }}/zap-report:/zap/wrk/:rw" \
            -v "${{ github.workspace }}/zap-rules.conf:/zap/wrk/zap-rules.conf:ro" \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
            -t http://localhost:3000 \
            -r zap-report.html \
            -c zap-rules.conf \
            -I \
            --autooff

      - name: Publicar relatório do ZAP
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-security-report
          path: zap-report/zap-report.html